export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const GET_ALL_GAMES = 'GET_ALL_GAMES';
export const GET_GAMES_ERROR = 'GET_GAMES_ERROR';

export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const CREATE_GAME_FAIL = 'CREATE_GAME_FAIL';
