// alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// library
export const GET_ALL_GAMES = 'GET_ALL_GAMES';
export const GET_GAMES_ERROR = 'GET_GAMES_ERROR';

// game
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const CREATE_GAME_FAIL = 'CREATE_GAME_FAIL';
export const JOIN_GAME_SUCCESS = 'JOIN_GAME_SUCCESS';
export const JOIN_GAME_FAIL = 'JOIN_GAME_FAIL';
export const GET_GAME_DATA = 'GET_GAME_DATA';
export const GET_GAME_DATA_FAIL = 'GET_GAME_DATA_FAIL';
export const END_GAME_SUCCESS = 'END_GAME_SUCCESS';
export const END_GAME_FAIL = 'END_GAME_FAIL';

// player
export const SET_INIT_PLAYER_STATE = 'SET_INIT_PLAYER_STATE';
export const SET_INIT_PLAYER_STATE_FAIL = 'SET_INIT_PLAYER_STATE_FAIL';
export const CREATE_PLAYER_SUCCESS = 'CREATE_PLAYER_SUCCESS';
export const CREATE_PLAYER_FAIL = 'CREATE_PLAYER_FAIL';
export const GET_PLAYER_DATA_SUCCESS = 'GET_PLAYER_DATA_SUCCESS';
export const SUBMIT_PLAYER_SCORE = 'SUBMIT_PLAYER_SCORE';
export const SUBMIT_PLAYER_SCORE_FAIL = 'SUBMIT_PLAYER_SCORE_FAIL';

// round
export const GET_CURRENT_ROUND_DATA = 'GET_CURRENT_ROUND_DATA';
export const GET_CURRENT_ROUND_DATA_FAIL = 'GET_CURRENT_ROUND_DATA_FAIL';
export const START_ROUND = 'START_ROUND';
export const START_ROUND_FAIL = 'START_ROUND_FAIL';
export const END_ROUND = 'END_ROUND';
export const END_ROUND_FAIL = 'END_ROUND_FAIL';
export const SET_WINNER = 'SET_WINNER';
export const SET_WINNER_FAIL = 'SET_WINNER_FAIL';
export const ADD_NEW_ROUND = 'ADD_NEW_ROUND';
export const ADD_NEW_ROUND_FAIL = 'ADD_NEW_ROUND_FAIL';
