// alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// library
export const GET_ALL_GAMES_SUCCESS = 'GET_ALL_GAMES_SUCCESS';
export const GET_GAMES_FAIL = 'GET_GAMES_FAIL';

// game
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const CREATE_GAME_FAIL = 'CREATE_GAME_FAIL';
export const JOIN_GAME_SUCCESS = 'JOIN_GAME_SUCCESS';
export const JOIN_GAME_FAIL = 'JOIN_GAME_FAIL';
export const GET_GAME_DATA_SUCCESS = 'GET_GAME_DATA_SUCCESS';
export const GET_GAME_DATA_FAIL = 'GET_GAME_DATA_FAIL';
export const END_GAME_SUCCESS = 'END_GAME_SUCCESS';
export const END_GAME_FAIL = 'END_GAME_FAIL';

// user
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const SET_INIT_USER_STATE_SUCCESS = 'SET_INIT_USER_STATE_SUCCESS';
export const SET_INIT_USER_STATE_FAIL = 'SET_INIT_USER_STATE_FAIL';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const SUBMIT_USER_SCORE_SUCCESS = 'SUBMIT_USER_SCORE_SUCCESS';
export const SUBMIT_USER_SCORE_FAIL = 'SUBMIT_USER_SCORE_FAIL';

// players
export const GET_ALL_PLAYERS_SUCCESS = 'GET_ALL_PLAYERS_SUCCESS';
export const GET_ALL_PLAYERS_FAIL = 'GET_ALL_PLAYERS_FAIL';
export const GM_CREATE_PLAYER_SUCCESS = 'GM_CREATE_PLAYER_SUCCESS';
export const GM_CREATE_PLAYER_FAIL = 'GM_CREATE_PLAYER_FAIL';
export const GM_SUBMIT_USER_SCORE_SUCCESS = 'GM_SUBMIT_USER_SCORE_SUCCESS';
export const GM_SUBMIT_USER_SCORE_FAIL = 'GM_SUBMIT_USER_SCORE_FAIL';

// round
export const SET_CURRENT_ROUND_DATA_SUCCESS = 'SET_CURRENT_ROUND_DATA_SUCCESS';
export const SET_CURRENT_ROUND_DATA_FAIL = 'SET_CURRENT_ROUND_DATA_FAIL';
export const START_ROUND_SUCCESS = 'START_ROUND_SUCCESS';
export const START_ROUND_FAIL = 'START_ROUND_FAIL';
export const END_ROUND_SUCCESS = 'END_ROUND_SUCCESS';
export const END_ROUND_FAIL = 'END_ROUND_FAIL';
export const SET_WINNER_SUCCESS = 'SET_WINNER_SUCCESS';
export const SET_WINNER_FAIL = 'SET_WINNER_FAIL';
export const ADD_NEW_ROUND_SUCCESS = 'ADD_NEW_ROUND_SUCCESS';
export const ADD_NEW_ROUND_FAIL = 'ADD_NEW_ROUND_FAIL';

// popups
export const TOGGLE_INFO_POPUP = 'TOGGLE_INFO_POPUP';
export const TOGGLE_NEW_PLAYER_POPUP = 'TOGGLE_NEW_PLAYER_POPUP';
export const TOGGLE_END_GAME_POPUP = 'TOGGLE_END_GAME_POPUP';
export const TOGGLE_PLAYER_SUBMIT_SCORE_POPUP =
  'TOGGLE_PLAYER_SUBMIT_SCORE_POPUP';
